version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      APP_DB_USER: "postgres"
      APP_DB_PASS: "postgres"
      APP_DB_NAME: "devops"
    ports:
      - "5432:5432"
    volumes:
      - .:/app
    working_dir: /app
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "profeta@indt.org.br"
      PGADMIN_DEFAULT_PASSWORD: "PR0FETA!"
    ports:
      - "15432:80"
    depends_on:
      - postgres
  angular:
    image: node:16-alpine
    ports: 
      - '4200:4200'
    volumes:
       - ./frontend:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm run start"
  nest:
    image: node:16-alpine
    ports: 
      - '3000:3000'
    volumes:
       - ./backend:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm run start:dev"
